---
# tasks file for nagios
- name: install nagios' dependent packages
  sudo: true
  apt: pkg={{item}} state=present force=true update_cache=yes
  with_items: nagios_packages

- name: install legacy packages
  sudo: true
  apt: pkg={{item}} state=present force=true update_cache=yes
  when: legacy | default(false)

# Create nagios users and groups.

